package com.taherajna.practice.games;

import org.junit.Assert;
import org.junit.Test;

public class SudokuNineBlockTraversalCompleteTest extends SudokuNineBlockTraversal {

  @Test
  public void testFormulaComplete_testI() {
    Assert.assertEquals(0, getI(0, 0));
    Assert.assertEquals(0, getI(0, 1));
    Assert.assertEquals(0, getI(0, 2));
    Assert.assertEquals(0, getI(3, 0));
    Assert.assertEquals(0, getI(3, 1));
    Assert.assertEquals(0, getI(3, 2));
    Assert.assertEquals(0, getI(6, 0));
    Assert.assertEquals(0, getI(6, 1));
    Assert.assertEquals(0, getI(6, 2));
    Assert.assertEquals(1, getI(0, 3));
    Assert.assertEquals(1, getI(0, 4));
    Assert.assertEquals(1, getI(0, 5));
    Assert.assertEquals(1, getI(3, 3));
    Assert.assertEquals(1, getI(3, 4));
    Assert.assertEquals(1, getI(3, 5));
    Assert.assertEquals(1, getI(6, 3));
    Assert.assertEquals(1, getI(6, 4));
    Assert.assertEquals(1, getI(6, 5));
    Assert.assertEquals(2, getI(0, 6));
    Assert.assertEquals(2, getI(0, 7));
    Assert.assertEquals(2, getI(0, 8));
    Assert.assertEquals(2, getI(3, 6));
    Assert.assertEquals(2, getI(3, 7));
    Assert.assertEquals(2, getI(3, 8));
    Assert.assertEquals(2, getI(6, 6));
    Assert.assertEquals(2, getI(6, 7));
    Assert.assertEquals(2, getI(6, 8));

    Assert.assertEquals(3, getI(1, 0));
    Assert.assertEquals(3, getI(1, 1));
    Assert.assertEquals(3, getI(1, 2));
    Assert.assertEquals(3, getI(4, 0));
    Assert.assertEquals(3, getI(4, 1));
    Assert.assertEquals(3, getI(4, 2));
    Assert.assertEquals(3, getI(7, 0));
    Assert.assertEquals(3, getI(7, 1));
    Assert.assertEquals(3, getI(7, 2));
    Assert.assertEquals(4, getI(1, 3));
    Assert.assertEquals(4, getI(1, 4));
    Assert.assertEquals(4, getI(1, 5));
    Assert.assertEquals(4, getI(4, 3));
    Assert.assertEquals(4, getI(4, 4));
    Assert.assertEquals(4, getI(4, 5));
    Assert.assertEquals(4, getI(7, 3));
    Assert.assertEquals(4, getI(7, 4));
    Assert.assertEquals(4, getI(7, 5));
    Assert.assertEquals(5, getI(1, 6));
    Assert.assertEquals(5, getI(1, 7));
    Assert.assertEquals(5, getI(1, 8));
    Assert.assertEquals(5, getI(4, 6));
    Assert.assertEquals(5, getI(4, 7));
    Assert.assertEquals(5, getI(4, 8));
    Assert.assertEquals(5, getI(7, 6));
    Assert.assertEquals(5, getI(7, 7));
    Assert.assertEquals(5, getI(7, 8));

    Assert.assertEquals(6, getI(2, 0));
    Assert.assertEquals(6, getI(2, 1));
    Assert.assertEquals(6, getI(2, 2));
    Assert.assertEquals(6, getI(5, 0));
    Assert.assertEquals(6, getI(5, 1));
    Assert.assertEquals(6, getI(5, 2));
    Assert.assertEquals(6, getI(8, 0));
    Assert.assertEquals(6, getI(8, 1));
    Assert.assertEquals(6, getI(8, 2));
    Assert.assertEquals(7, getI(2, 3));
    Assert.assertEquals(7, getI(2, 4));
    Assert.assertEquals(7, getI(2, 5));
    Assert.assertEquals(7, getI(5, 3));
    Assert.assertEquals(7, getI(5, 4));
    Assert.assertEquals(7, getI(5, 5));
    Assert.assertEquals(7, getI(8, 3));
    Assert.assertEquals(7, getI(8, 4));
    Assert.assertEquals(7, getI(8, 5));
    Assert.assertEquals(8, getI(2, 6));
    Assert.assertEquals(8, getI(2, 7));
    Assert.assertEquals(8, getI(2, 8));
    Assert.assertEquals(8, getI(5, 6));
    Assert.assertEquals(8, getI(5, 7));
    Assert.assertEquals(8, getI(5, 8));
    Assert.assertEquals(8, getI(8, 6));
    Assert.assertEquals(8, getI(8, 7));
    Assert.assertEquals(8, getI(8, 8));
  }

  @Test
  public void testFormulaComplete_testJ() {
    Assert.assertEquals(0, getJ(0, 0));
    Assert.assertEquals(1, getJ(0, 1));
    Assert.assertEquals(2, getJ(0, 2));
    Assert.assertEquals(3, getJ(3, 0));
    Assert.assertEquals(4, getJ(3, 1));
    Assert.assertEquals(5, getJ(3, 2));
    Assert.assertEquals(6, getJ(6, 0));
    Assert.assertEquals(7, getJ(6, 1));
    Assert.assertEquals(8, getJ(6, 2));
    Assert.assertEquals(0, getJ(0, 3));
    Assert.assertEquals(1, getJ(0, 4));
    Assert.assertEquals(2, getJ(0, 5));
    Assert.assertEquals(3, getJ(3, 3));
    Assert.assertEquals(4, getJ(3, 4));
    Assert.assertEquals(5, getJ(3, 5));
    Assert.assertEquals(6, getJ(6, 3));
    Assert.assertEquals(7, getJ(6, 4));
    Assert.assertEquals(8, getJ(6, 5));
    Assert.assertEquals(0, getJ(0, 6));
    Assert.assertEquals(1, getJ(0, 7));
    Assert.assertEquals(2, getJ(0, 8));
    Assert.assertEquals(3, getJ(3, 6));
    Assert.assertEquals(4, getJ(3, 7));
    Assert.assertEquals(5, getJ(3, 8));
    Assert.assertEquals(6, getJ(6, 6));
    Assert.assertEquals(7, getJ(6, 7));
    Assert.assertEquals(8, getJ(6, 8));

    Assert.assertEquals(0, getJ(1, 0));
    Assert.assertEquals(1, getJ(1, 1));
    Assert.assertEquals(2, getJ(1, 2));
    Assert.assertEquals(3, getJ(4, 0));
    Assert.assertEquals(4, getJ(4, 1));
    Assert.assertEquals(5, getJ(4, 2));
    Assert.assertEquals(6, getJ(7, 0));
    Assert.assertEquals(7, getJ(7, 1));
    Assert.assertEquals(8, getJ(7, 2));
    Assert.assertEquals(0, getJ(1, 3));
    Assert.assertEquals(1, getJ(1, 4));
    Assert.assertEquals(2, getJ(1, 5));
    Assert.assertEquals(3, getJ(4, 3));
    Assert.assertEquals(4, getJ(4, 4));
    Assert.assertEquals(5, getJ(4, 5));
    Assert.assertEquals(6, getJ(7, 3));
    Assert.assertEquals(7, getJ(7, 4));
    Assert.assertEquals(8, getJ(7, 5));
    Assert.assertEquals(0, getJ(1, 6));
    Assert.assertEquals(1, getJ(1, 7));
    Assert.assertEquals(2, getJ(1, 8));
    Assert.assertEquals(3, getJ(4, 6));
    Assert.assertEquals(4, getJ(4, 7));
    Assert.assertEquals(5, getJ(4, 8));
    Assert.assertEquals(6, getJ(7, 6));
    Assert.assertEquals(7, getJ(7, 7));
    Assert.assertEquals(8, getJ(7, 8));

    Assert.assertEquals(0, getJ(2, 0));
    Assert.assertEquals(1, getJ(2, 1));
    Assert.assertEquals(2, getJ(2, 2));
    Assert.assertEquals(3, getJ(5, 0));
    Assert.assertEquals(4, getJ(5, 1));
    Assert.assertEquals(5, getJ(5, 2));
    Assert.assertEquals(6, getJ(8, 0));
    Assert.assertEquals(7, getJ(8, 1));
    Assert.assertEquals(8, getJ(8, 2));
    Assert.assertEquals(0, getJ(2, 3));
    Assert.assertEquals(1, getJ(2, 4));
    Assert.assertEquals(2, getJ(2, 5));
    Assert.assertEquals(3, getJ(5, 3));
    Assert.assertEquals(4, getJ(5, 4));
    Assert.assertEquals(5, getJ(5, 5));
    Assert.assertEquals(6, getJ(8, 3));
    Assert.assertEquals(7, getJ(8, 4));
    Assert.assertEquals(8, getJ(8, 5));
    Assert.assertEquals(0, getJ(2, 6));
    Assert.assertEquals(1, getJ(2, 7));
    Assert.assertEquals(2, getJ(2, 8));
    Assert.assertEquals(3, getJ(5, 6));
    Assert.assertEquals(4, getJ(5, 7));
    Assert.assertEquals(5, getJ(5, 8));
    Assert.assertEquals(6, getJ(8, 6));
    Assert.assertEquals(7, getJ(8, 7));
    Assert.assertEquals(8, getJ(8, 8));
  }
}
